import { Link } from "@tanstack/react-router";
import { ArrowRight, BedDouble, CarFront, CalendarDays, MapPin, Star } from "lucide-react";
import { Button } from "@/components/ui/button";
import { TrekoFooter, TrekoNavbar } from "@/components/TrekoChrome";
import { type DestinationDetails, getDestinationDetails } from "@/data/destination-details";

function SectionHeading({ label, title, description }: { label: string; title: string; description?: string }) {
  return <div className="mb-7"><p className="section-label">{label}</p><h2 className="mt-2 font-display text-3xl font-semibold md:text-4xl">{title}</h2>{description && <p className="mt-3 max-w-2xl leading-7 text-muted-foreground">{description}</p>}</div>;
}

function DestinationNotFound() {
  return <main className="min-h-screen bg-background"><TrekoNavbar /><section className="mx-auto flex min-h-[65vh] max-w-2xl items-center px-5 py-20 text-center md:px-8"><div className="w-full rounded-3xl border border-dashed border-border bg-secondary px-6 py-16"><MapPin className="mx-auto size-10 text-primary" /><p className="section-label mt-5">A small detour</p><h1 className="mt-2 font-display text-3xl font-semibold md:text-4xl">Destination Not Found</h1><p className="mx-auto mt-4 max-w-md leading-7 text-muted-foreground">We couldn't find that destination yet. Explore Treko's growing collection of Indian journeys instead.</p><Button asChild className="mt-7 rounded-full"><Link to="/destinations">Explore Destinations <ArrowRight /></Link></Button></div></section><TrekoFooter /></main>;
}

function Hero({ destination }: { destination: DestinationDetails }) {
  return <section className="relative isolate overflow-hidden bg-foreground text-background"><TrekoNavbar /><img src={destination.image} alt="" className="absolute inset-0 -z-20 h-full w-full object-cover opacity-35" /><div className="absolute inset-0 -z-10 bg-gradient-to-r from-foreground via-foreground/85 to-foreground/35" /><div className="mx-auto grid max-w-7xl gap-10 px-5 py-16 md:grid-cols-[1.05fr_.95fr] md:px-8 md:py-24"><div className="flex max-w-2xl flex-col justify-center"><p className="flex items-center gap-2 text-sm font-bold text-primary-foreground/75"><MapPin className="size-4 text-primary" />{destination.state}</p><h1 className="mt-5 font-display text-5xl font-semibold leading-none md:text-7xl">{destination.name}</h1><p className="mt-6 max-w-xl text-lg leading-8 text-background/75">{destination.description}</p><div className="mt-8 flex flex-wrap gap-3"><Button asChild className="h-12 rounded-full px-6"><a href="/plan-trip">Plan Your Trip <ArrowRight /></a></Button><span className="inline-flex items-center rounded-full border border-background/20 px-4 text-sm font-semibold text-background/85"><CalendarDays className="mr-2 size-4 text-primary" />Best time: {destination.bestTime}</span></div></div><div className="hidden items-end md:flex"><div className="w-full overflow-hidden rounded-3xl border border-background/15 shadow-hero"><img src={destination.image} alt={destination.name} className="aspect-[4/3] h-full w-full object-cover" /></div></div></div></section>;
}

function Places({ destination }: { destination: DestinationDetails }) {
  return <section><SectionHeading label="See & experience" title="Places to Visit" description={`Make time for these memorable corners of ${destination.name}.`} /><div className="grid gap-5 md:grid-cols-3">{destination.placesToVisit.map(place => <article key={place.name} className="overflow-hidden rounded-2xl border border-border bg-card p-5 shadow-card"><span className="tag">{place.tag ?? "Discover"}</span><h3 className="mt-5 font-display text-2xl font-semibold">{place.name}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{place.description}</p></article>)}</div></section>;
}

function Stays({ destination }: { destination: DestinationDetails }) {
  return <section><SectionHeading label="Rest well" title="Where to Stay" description="Comfortable, well-located stays to help you make the most of your trip." /><div className="grid gap-5 md:grid-cols-2">{destination.stays.map(stay => <article key={stay.name} className="group overflow-hidden rounded-2xl border border-border bg-card shadow-card transition-all duration-300 hover:-translate-y-1 hover:shadow-card-hover sm:flex"><img src={stay.image} alt={stay.name} className="aspect-[4/3] w-full object-cover sm:w-48" /><div className="flex flex-1 flex-col p-5"><div className="flex items-start justify-between gap-3"><div><h3 className="font-display text-xl font-semibold">{stay.name}</h3><p className="mt-1 flex items-center gap-1 text-sm text-muted-foreground"><MapPin className="size-3.5 text-primary" />{stay.location}</p></div><span className="flex shrink-0 items-center gap-1 rounded-full bg-secondary px-2.5 py-1 text-xs font-bold"><Star className="size-3 fill-primary text-primary" />{stay.rating}</span></div><div className="mt-5 flex items-center justify-between gap-3"><p className="text-sm font-bold text-primary">{stay.price}</p><Button variant="outline" size="sm" className="rounded-full">View Stay</Button></div></div></article>)}</div></section>;
}

function Operators({ destination }: { destination: DestinationDetails }) {
  return <section><SectionHeading label="Move locally" title="Local Travel & Cab Operators" description="Connect with local options for transfers, sightseeing and day trips." /><div className="grid gap-5 md:grid-cols-2">{destination.cabOperators.map(operator => <article key={operator.name} className="rounded-2xl border border-border bg-secondary p-6 shadow-card"><div className="flex items-start justify-between gap-3"><div><div className="grid size-11 place-items-center rounded-xl bg-card text-primary shadow-sm"><CarFront className="size-5" /></div><h3 className="mt-4 font-display text-xl font-semibold">{operator.name}</h3></div><span className="flex items-center gap-1 rounded-full bg-card px-2.5 py-1 text-xs font-bold shadow-sm"><Star className="size-3 fill-primary text-primary" />{operator.rating}</span></div><p className="mt-3 text-sm leading-6 text-muted-foreground">{operator.description}</p><p className="mt-4 flex items-center gap-2 text-sm font-semibold"><CarFront className="size-4 text-primary" />{operator.vehicles}</p><Button variant="outline" className="mt-5 rounded-full">View Operator</Button></article>)}</div></section>;
}

function Nearby({ destination }: { destination: DestinationDetails }) {
  const nearby = destination.nearbySlugs.map(getDestinationDetails).filter((item): item is DestinationDetails => Boolean(item));
  return <section><SectionHeading label="Keep exploring" title="Nearby Destinations" /><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{nearby.map(item => <Link key={item.slug} to="/destinations/$slug" params={{ slug: item.slug }} className="group overflow-hidden rounded-2xl border border-border bg-card shadow-card transition-all duration-300 hover:-translate-y-1 hover:shadow-card-hover"><img src={item.image} alt={item.name} className="aspect-[16/9] w-full object-cover transition-transform duration-500 group-hover:scale-105" /><div className="flex items-center justify-between p-5"><div><p className="text-xs font-bold uppercase text-primary">{item.state}</p><h3 className="mt-1 font-display text-2xl font-semibold">{item.name}</h3></div><ArrowRight className="text-primary transition-transform group-hover:translate-x-1" /></div></Link>)}</div></section>;
}

export function DestinationDetailsPage({ slug }: { slug: string }) {
  const destination = getDestinationDetails(slug);
  if (!destination) return <DestinationNotFound />;
  return <main className="overflow-hidden"><Hero destination={destination} /><div className="mx-auto max-w-7xl space-y-20 px-5 py-16 md:px-8 md:py-20"><section className="grid gap-8 rounded-3xl bg-secondary p-6 md:grid-cols-[.65fr_1.35fr] md:p-9"><div><p className="section-label">About {destination.name}</p><h2 className="mt-2 font-display text-3xl font-semibold">Travel with the local rhythm.</h2></div><div><p className="leading-8 text-muted-foreground">{destination.about}</p><div className="mt-6 flex flex-wrap gap-2"><span className="tag"><BedDouble />{destination.accommodationCount} stays</span><span className="tag"><CarFront />{destination.cabOperatorCount} cab operators</span></div></div></section><Places destination={destination} /><Stays destination={destination} /><Operators destination={destination} /><Nearby destination={destination} /><section className="rounded-3xl bg-foreground px-6 py-14 text-center text-background md:px-12"><p className="section-label section-label-dark">Your journey, your way</p><h2 className="mx-auto mt-3 max-w-2xl font-display text-3xl font-semibold md:text-5xl">Ready to plan your {destination.name} trip?</h2><p className="mx-auto mt-4 max-w-xl text-background/65">Start shaping your escape with stays, local travel and the places that make this destination special.</p><Button asChild className="mt-8 h-12 rounded-full px-7"><a href="/plan-trip">Plan Your Trip <ArrowRight /></a></Button></section></div><TrekoFooter /></main>;
}