import { useMemo, useState } from "react";
import { BedDouble, CarFront, MapPin, Search, Star, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { TrekoFooter, TrekoNavbar } from "@/components/TrekoChrome";
import { cabOperatorListings, stayListings, type CabOperatorListing, type StayListing } from "@/data/listings";

const ALL = "all";

function ListingHero({ title, subtitle, placeholder, icon: Icon, query, onQueryChange }: { title: string; subtitle: string; placeholder: string; icon: typeof BedDouble; query: string; onQueryChange: (value: string) => void }) {
  return <section className="bg-hero"><TrekoNavbar /><div className="mx-auto max-w-7xl px-5 pb-14 pt-12 md:px-8 md:pb-16 md:pt-16"><div className="max-w-2xl"><p className="section-label flex items-center gap-2"><Icon className="size-4" />Discover with Treko</p><h1 className="mt-3 font-display text-4xl font-semibold md:text-6xl">{title}</h1><p className="mt-4 max-w-xl text-base leading-7 text-muted-foreground md:text-lg">{subtitle}</p><div className="relative mt-7"><Search className="pointer-events-none absolute left-5 top-1/2 size-5 -translate-y-1/2 text-primary" /><input value={query} onChange={event => onQueryChange(event.target.value)} placeholder={placeholder} className="h-14 w-full rounded-2xl border border-border bg-card px-14 text-sm font-medium shadow-search outline-none focus:border-primary" />{query && <button onClick={() => onQueryChange("")} aria-label="Clear search" className="absolute right-4 top-1/2 -translate-y-1/2 rounded-full p-2 text-muted-foreground hover:bg-secondary"><X className="size-4" /></button>}</div></div></div></section>;
}

function EmptyState({ title, onClear }: { title: string; onClear: () => void }) {
 return <div className="rounded-2xl border border-dashed border-border bg-secondary px-6 py-16 text-center"><Search className="mx-auto size-8 text-primary" /><h2 className="mt-4 font-display text-2xl font-semibold">{title}</h2><p className="mt-2 text-sm text-muted-foreground">Try a different search or clear your filters.</p><Button variant="outline" onClick={onClear} className="mt-6 rounded-full">Clear search & filters</Button></div>;
}

export function StaysPage() {
 const [query, setQuery] = useState(""); const [destination, setDestination] = useState(ALL); const [rating, setRating] = useState(ALL);
 const destinations = useMemo(() => [...new Set(stayListings.map(stay => stay.destinationName))].sort(), []);
 const filtered = useMemo(() => stayListings.filter(stay => {
  const term = query.toLowerCase().trim(); const matches = !term || [stay.name, stay.destinationName, stay.state, stay.description].some(value => value.toLowerCase().includes(term));
  return matches && (destination === ALL || stay.destinationName === destination) && (rating === ALL || Number(stay.rating) >= Number(rating));
 }), [query, destination, rating]);
 const clear = () => { setQuery(""); setDestination(ALL); setRating(ALL); };
 return <main className="overflow-hidden"><ListingHero title="Find Your Stay" subtitle="Discover comfortable stays across destinations in India." placeholder="Search stays, cities or destinations..." icon={BedDouble} query={query} onQueryChange={setQuery} /><div className="mx-auto max-w-7xl px-5 py-16 md:px-8 md:py-20"><div className="mb-8 flex flex-col justify-between gap-4 rounded-2xl border border-border bg-secondary p-4 sm:flex-row sm:items-end"><div className="grid flex-1 gap-3 sm:grid-cols-2"><div><label className="mb-1.5 block text-[10px] font-bold uppercase text-muted-foreground">Destination</label><Select value={destination} onValueChange={setDestination}><SelectTrigger className="h-11 rounded-xl bg-card"><SelectValue /></SelectTrigger><SelectContent><SelectItem value={ALL}>All destinations</SelectItem>{destinations.map(item => <SelectItem key={item} value={item}>{item}</SelectItem>)}</SelectContent></Select></div><div><label className="mb-1.5 block text-[10px] font-bold uppercase text-muted-foreground">Minimum rating</label><Select value={rating} onValueChange={setRating}><SelectTrigger className="h-11 rounded-xl bg-card"><SelectValue /></SelectTrigger><SelectContent><SelectItem value={ALL}>Any rating</SelectItem><SelectItem value="4.5">4.5 and above</SelectItem><SelectItem value="4">4.0 and above</SelectItem></SelectContent></Select></div></div><p className="text-sm text-muted-foreground">{filtered.length} stays</p></div>{filtered.length ? <div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{filtered.map(stay => <StayCard key={stay.id} stay={stay} />)}</div> : <EmptyState title="No stays found" onClear={clear} />}</div><TrekoFooter /></main>;
}

function StayCard({ stay }: { stay: StayListing }) {
 return <article className="group flex h-full flex-col overflow-hidden rounded-2xl border border-border bg-card shadow-card transition-all duration-300 hover:-translate-y-1 hover:shadow-card-hover"><img src={stay.image} alt={stay.name} loading="lazy" className="aspect-[16/10] w-full object-cover transition-transform duration-500 group-hover:scale-105" /><div className="flex flex-1 flex-col p-5"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase text-primary">{stay.propertyType}</p><h2 className="mt-1 font-display text-2xl font-semibold">{stay.name}</h2></div><span className="flex items-center gap-1 rounded-full bg-secondary px-2.5 py-1 text-xs font-bold"><Star className="size-3 fill-primary text-primary" />{stay.rating}</span></div><p className="mt-2 flex items-center gap-1 text-sm text-muted-foreground"><MapPin className="size-3.5 text-primary" />{stay.destinationName}, {stay.state}</p><p className="mt-3 flex-1 text-sm leading-6 text-muted-foreground">{stay.description}</p><div className="mt-4 flex flex-wrap gap-2">{stay.amenities.map(item => <span key={item} className="tag">{item}</span>)}</div><div className="mt-5 flex items-center justify-between"><p className="text-sm font-bold text-primary">{stay.price}<span className="font-medium text-muted-foreground"> / night</span></p><Button variant="outline" size="sm" className="rounded-full">View Stay</Button></div></div></article>;
}

export function CabOperatorsPage() {
 const [query, setQuery] = useState(""); const [destination, setDestination] = useState(ALL);
 const destinations = useMemo(() => [...new Set(cabOperatorListings.map(operator => operator.destinationName))].sort(), []);
 const filtered = useMemo(() => cabOperatorListings.filter(operator => { const term = query.toLowerCase().trim(); return (!term || [operator.name, operator.destinationName, operator.state, operator.description, operator.vehicleTypes].some(value => value.toLowerCase().includes(term))) && (destination === ALL || operator.destinationName === destination); }), [query, destination]);
 const clear = () => { setQuery(""); setDestination(ALL); };
 return <main className="overflow-hidden"><ListingHero title="Travel Around Your Destination" subtitle="Find trusted local cab and travel operators for your journey." placeholder="Search operators, service areas or destinations..." icon={CarFront} query={query} onQueryChange={setQuery} /><div className="mx-auto max-w-7xl px-5 py-16 md:px-8 md:py-20"><div className="mb-8 flex flex-col justify-between gap-4 rounded-2xl border border-border bg-secondary p-4 sm:flex-row sm:items-end"><div className="w-full max-w-sm"><label className="mb-1.5 block text-[10px] font-bold uppercase text-muted-foreground">Destination</label><Select value={destination} onValueChange={setDestination}><SelectTrigger className="h-11 rounded-xl bg-card"><SelectValue /></SelectTrigger><SelectContent><SelectItem value={ALL}>All destinations</SelectItem>{destinations.map(item => <SelectItem key={item} value={item}>{item}</SelectItem>)}</SelectContent></Select></div><p className="text-sm text-muted-foreground">{filtered.length} cab operators</p></div>{filtered.length ? <div className="grid gap-5 md:grid-cols-2 lg:grid-cols-3">{filtered.map(operator => <OperatorCard key={operator.id} operator={operator} />)}</div> : <EmptyState title="No cab operators found" onClear={clear} />}</div><TrekoFooter /></main>;
}

function OperatorCard({ operator }: { operator: CabOperatorListing }) {
 return <article className="flex h-full flex-col rounded-2xl border border-border bg-card p-6 shadow-card transition-all duration-300 hover:-translate-y-1 hover:shadow-card-hover"><div className="flex items-start justify-between gap-3"><div className="grid size-12 place-items-center rounded-xl bg-secondary text-primary"><CarFront className="size-6" /></div><span className="flex items-center gap-1 rounded-full bg-secondary px-2.5 py-1 text-xs font-bold"><Star className="size-3 fill-primary text-primary" />{operator.rating}</span></div><h2 className="mt-5 font-display text-2xl font-semibold">{operator.name}</h2><p className="mt-2 flex items-center gap-1 text-sm text-muted-foreground"><MapPin className="size-3.5 text-primary" />{operator.destinationName}, {operator.state}</p><p className="mt-3 flex-1 text-sm leading-6 text-muted-foreground">{operator.description}</p><p className="mt-5 flex items-center gap-2 text-sm font-semibold"><CarFront className="size-4 text-primary" />{operator.vehicleTypes}</p><div className="mt-4 flex flex-wrap gap-2">{operator.serviceTypes.map(item => <span key={item} className="tag">{item}</span>)}</div><Button variant="outline" className="mt-6 w-full rounded-full">View Operator</Button></article>;
}