/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CabOperatorsRouteImport } from './routes/cab-operators'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PartnerRouteImport } from './routes/partner'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as StaysRouteImport } from './routes/stays'
import { Route as DestinationIdRouteImport } from './routes/destination/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CabOperatorsRoute = CabOperatorsRouteImport.update({
  id: '/cab-operators',
  path: '/cab-operators',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerRoute = PartnerRouteImport.update({
  id: '/partner',
  path: '/partner',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const StaysRoute = StaysRouteImport.update({
  id: '/stays',
  path: '/stays',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationIdRoute = DestinationIdRouteImport.update({
  id: '/destination/$id',
  path: '/destination/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cab-operators': typeof CabOperatorsRoute
  '/explore': typeof ExploreRoute
  '/login': typeof LoginRoute
  '/partner': typeof PartnerRoute
  '/register': typeof RegisterRoute
  '/stays': typeof StaysRoute
  '/destination/$id': typeof DestinationIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cab-operators': typeof CabOperatorsRoute
  '/explore': typeof ExploreRoute
  '/login': typeof LoginRoute
  '/partner': typeof PartnerRoute
  '/register': typeof RegisterRoute
  '/stays': typeof StaysRoute
  '/destination/$id': typeof DestinationIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cab-operators': typeof CabOperatorsRoute
  '/explore': typeof ExploreRoute
  '/login': typeof LoginRoute
  '/partner': typeof PartnerRoute
  '/register': typeof RegisterRoute
  '/stays': typeof StaysRoute
  '/destination/$id': typeof DestinationIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cab-operators'
    | '/explore'
    | '/login'
    | '/partner'
    | '/register'
    | '/stays'
    | '/destination/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cab-operators'
    | '/explore'
    | '/login'
    | '/partner'
    | '/register'
    | '/stays'
    | '/destination/$id'
  id:
    | '__root__'
    | '/'
    | '/cab-operators'
    | '/explore'
    | '/login'
    | '/partner'
    | '/register'
    | '/stays'
    | '/destination/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CabOperatorsRoute: typeof CabOperatorsRoute
  ExploreRoute: typeof ExploreRoute
  LoginRoute: typeof LoginRoute
  PartnerRoute: typeof PartnerRoute
  RegisterRoute: typeof RegisterRoute
  StaysRoute: typeof StaysRoute
  DestinationIdRoute: typeof DestinationIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cab-operators': {
      id: '/cab-operators'
      path: '/cab-operators'
      fullPath: '/cab-operators'
      preLoaderRoute: typeof CabOperatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner': {
      id: '/partner'
      path: '/partner'
      fullPath: '/partner'
      preLoaderRoute: typeof PartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stays': {
      id: '/stays'
      path: '/stays'
      fullPath: '/stays'
      preLoaderRoute: typeof StaysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destination/$id': {
      id: '/destination/$id'
      path: '/destination/$id'
      fullPath: '/destination/$id'
      preLoaderRoute: typeof DestinationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CabOperatorsRoute: CabOperatorsRoute,
  ExploreRoute: ExploreRoute,
  LoginRoute: LoginRoute,
  PartnerRoute: PartnerRoute,
  RegisterRoute: RegisterRoute,
  StaysRoute: StaysRoute,
  DestinationIdRoute: DestinationIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
