/* eslint-disable */
// @ts-nocheck
// This file is automatically generated by TanStack Router.
import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as DestinationsRouteImport } from './routes/destinations'
import { Route as DestinationsSlugRouteImport } from './routes/destinations/$slug'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SignupRouteImport } from './routes/signup'

const IndexRoute = IndexRouteImport.update({ id: '/', path: '/', getParentRoute: () => rootRouteImport } as any)
const ExploreRoute = ExploreRouteImport.update({ id: '/explore', path: '/explore', getParentRoute: () => rootRouteImport } as any)
const DestinationsRoute = DestinationsRouteImport.update({ id: '/destinations', path: '/destinations', getParentRoute: () => rootRouteImport } as any)
const DestinationsSlugRoute = DestinationsSlugRouteImport.update({ id: '/destinations/$slug', path: '/destinations/$slug', getParentRoute: () => rootRouteImport } as any)
const LoginRoute = LoginRouteImport.update({ id: '/login', path: '/login', getParentRoute: () => rootRouteImport } as any)
const SignupRoute = SignupRouteImport.update({ id: '/signup', path: '/signup', getParentRoute: () => rootRouteImport } as any)

export interface FileRoutesByFullPath { '/': typeof IndexRoute; '/destinations': typeof DestinationsRoute; '/destinations/$slug': typeof DestinationsSlugRoute; '/explore': typeof ExploreRoute; '/login': typeof LoginRoute; '/signup': typeof SignupRoute }
export interface FileRoutesByTo { '/': typeof IndexRoute; '/destinations': typeof DestinationsRoute; '/destinations/$slug': typeof DestinationsSlugRoute; '/explore': typeof ExploreRoute; '/login': typeof LoginRoute; '/signup': typeof SignupRoute }
export interface FileRoutesById { __root__: typeof rootRouteImport; '/': typeof IndexRoute; '/destinations': typeof DestinationsRoute; '/destinations/$slug': typeof DestinationsSlugRoute; '/explore': typeof ExploreRoute; '/login': typeof LoginRoute; '/signup': typeof SignupRoute }
export interface FileRouteTypes { fileRoutesByFullPath: FileRoutesByFullPath; fullPaths: '/' | '/destinations' | '/destinations/$slug' | '/explore' | '/login' | '/signup'; fileRoutesByTo: FileRoutesByTo; to: '/' | '/destinations' | '/destinations/$slug' | '/explore' | '/login' | '/signup'; id: '__root__' | '/' | '/destinations' | '/destinations/$slug' | '/explore' | '/login' | '/signup'; fileRoutesById: FileRoutesById }
export interface RootRouteChildren { IndexRoute: typeof IndexRoute; DestinationsRoute: typeof DestinationsRoute; DestinationsSlugRoute: typeof DestinationsSlugRoute; ExploreRoute: typeof ExploreRoute; LoginRoute: typeof LoginRoute; SignupRoute: typeof SignupRoute }
declare module '@tanstack/react-router' { interface FileRoutesByPath {
  '/': { id: '/'; path: '/'; fullPath: '/'; preLoaderRoute: typeof IndexRouteImport; parentRoute: typeof rootRouteImport }
  '/destinations': { id: '/destinations'; path: '/destinations'; fullPath: '/destinations'; preLoaderRoute: typeof DestinationsRouteImport; parentRoute: typeof rootRouteImport }
  '/destinations/$slug': { id: '/destinations/$slug'; path: '/destinations/$slug'; fullPath: '/destinations/$slug'; preLoaderRoute: typeof DestinationsSlugRouteImport; parentRoute: typeof rootRouteImport }
  '/explore': { id: '/explore'; path: '/explore'; fullPath: '/explore'; preLoaderRoute: typeof ExploreRouteImport; parentRoute: typeof rootRouteImport }
  '/login': { id: '/login'; path: '/login'; fullPath: '/login'; preLoaderRoute: typeof LoginRouteImport; parentRoute: typeof rootRouteImport }
  '/signup': { id: '/signup'; path: '/signup'; fullPath: '/signup'; preLoaderRoute: typeof SignupRouteImport; parentRoute: typeof rootRouteImport }
} }
const rootRouteChildren: RootRouteChildren = { IndexRoute, DestinationsRoute, DestinationsSlugRoute, ExploreRoute, LoginRoute, SignupRoute }
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)._addFileTypes<FileRouteTypes>()
import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' { interface Register { ssr: true; router: Awaited<ReturnType<typeof getRouter>>; config: Awaited<ReturnType<typeof startInstance.getOptions>> } }
